import React from 'react';
import {
  Mosaic,
  MosaicWindow,
  MosaicZeroState,
  MosaicTabs,
  DraggableTab,
  Separator,
  ExpandButton,
  RemoveButton,
  ReplaceButton,
  SplitButton,
  AddTabButton,
  TabSplitButton,
  TabRemoveButton,
  TabExpandButton,
  TabDragButton,
  DefaultToolbarButton,
  MosaicContext,
  MosaicWindowContext,
  createBalancedTreeFromLeaves,
  getLeaves,
  getNodeAtPath,
  getParentNode,
  getParentPath,
  isSplitNode,
  isTabsNode,
  updateTree,
  createRemoveUpdate,
  createExpandUpdate,
  createHideUpdate,
  createDragToUpdates,
  convertLegacyToNary,
  DEFAULT_CONTROLS_WITH_CREATION,
  DEFAULT_CONTROLS_WITHOUT_CREATION,
  DEFAULT_CONTROLS_IN_TABS,
  createDefaultTabsControls,
} from 'react-mosaic-component';

// Add default React imports here so snippets can destructure useState etc.
// Anything referenced by a ```tsx live fence must live in this object.
const ReactLiveScope: Record<string, unknown> = {
  React,
  ...React,
  // Components
  Mosaic,
  MosaicWindow,
  MosaicZeroState,
  MosaicTabs,
  DraggableTab,
  // Toolbar buttons
  Separator,
  ExpandButton,
  RemoveButton,
  ReplaceButton,
  SplitButton,
  AddTabButton,
  TabSplitButton,
  TabRemoveButton,
  TabExpandButton,
  TabDragButton,
  DefaultToolbarButton,
  // Context
  MosaicContext,
  MosaicWindowContext,
  // Tree utilities
  createBalancedTreeFromLeaves,
  getLeaves,
  getNodeAtPath,
  getParentNode,
  getParentPath,
  isSplitNode,
  isTabsNode,
  // Update helpers
  updateTree,
  createRemoveUpdate,
  createExpandUpdate,
  createHideUpdate,
  createDragToUpdates,
  convertLegacyToNary,
  // Toolbar presets
  DEFAULT_CONTROLS_WITH_CREATION,
  DEFAULT_CONTROLS_WITHOUT_CREATION,
  DEFAULT_CONTROLS_IN_TABS,
  createDefaultTabsControls,
};

export default ReactLiveScope;
